- name: Restore Cisco NXOS from backup
  hosts: nxos
  gather_facts: no
  vars_files:
  - vars/main.yml
  tasks:

  - name: Find latest backup filename
    ansible.builtin.find:
      paths: "{{ backup_server_folder }}"
      file_type: file
      # patterns: '*'
      # hidden: true
      use_regex: false
    delegate_to: "{{ backup_server }}"
    become: yes
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
    register: backup_files

  - name: Get lastest backup ({{ (backup_files.files|last).path }})
    set_fact: 
      backup_file: "{{ (backup_files.files|last).path }}"

  - name: Fetch config from backup
    fetch:
      src: "{{ backup_file }}"
      dest: "/tmp/"
      flat: true
    when: backup_files | length > 0 
    delegate_to: "{{ backup_server }}"
    vars:
      ansible_user: "{{ backup_server_user }}"
      ansible_ssh_pass: "{{ backup_server_pass }}"
    register: tmp_backup_file

  - name: Config nxos router with backup
    cisco.nxos.nxos_config:
      src: "{{ tmp_backup_file.dest }}"
      save_when: changed
